language: php

php:
  - 7.1
  - 7.2

env:
  matrix:
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)